version: '3'

services:

  devenv:
    image: uleodolter/primo-explore-devenv-docker
    environment:
      PROXY: ${PROXY}
      VIEW: ${VIEW}
      GULP_BROWSERIFY: ${GULP_BROWSERIFY}
      GULP_USESCSS: ${GULP_USESCSS}
    ports:
      - 8003:8003 # used to view the application
      - 3001:3001 # used to view the browsersync dashboard
    volumes:
      - ./:/app/primo-explore-devenv/packages # used to access generated package .zip files
      - ./:/app/primo-explore-devenv/primo-explore/custom/${VIEW}
#     - ../primo-explore-central:/app/primo-explore-devenv/primo-explore/custom/CENTRAL_PACKAGE
